# ~/.bashrc: executed by bash(1) for non-login shells.

# setting ls to be colorized
export LS_OPTIONS='--color=auto'

#alias
alias ls='ls $LS_OPTIONS'
alias ll='ls $LS_OPTIONS -l'
alias l='ls $LS_OPTIONS -lA'

alias g=git
alias gs='git status'
alias gdiff='git diff --cached'
alias grc='git rebase --continue'
alias gra='git rebase --abort'
alias gca='git commit --amend'
alias gcm='git commit -m'
alias log1='git log --oneline -n20'
alias fetch='git fetch --all -ap'

#git configuration
git config --global core.whitespace blank-at-eol,blank-at-eof,space-before-tab && \
git config --global pull.rebase false && \
git config --global init.defaultbranch main && \
git config --global core.pager more

export FABRIC_SAMPLES_DIR=$GOPATH/src/github.com/devcontainer/fabric-samples
export PATH=$FABRIC_SAMPLES_DIR/bin:$PATH
export FABRIC_CFG_PATH=$FABRIC_SAMPLES_DIR/config
export TEST_NETWORK_PATH=$FABRIC_SAMPLES_DIR/test-network
export CORE_PEER_TLS_ENABLED=true
export CORE_PEER_LOCALMSPID="Org1MSP"
export CORE_PEER_TLS_ROOTCERT_FILE=${TEST_NETWORK_PATH}/organizations/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/ca.crt
export CORE_PEER_MSPCONFIGPATH=${TEST_NETWORK_PATH}/organizations/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp
export CORE_PEER_ADDRESS=localhost:7051
export CORE_ORDERER_ADDRESS=localhost:7050

# Go Private Modules setup
export GOPRIVATE=dev.azure.com/grupoEPM/*
export GONOPROXY=dev.azure.com/grupoEPM/*
export GONOSUMDB=dev.azure.com/grupoEPM/*