apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: update-secrets
  namespace: hlf
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    resourceNames: ["hlf-genesis-block"]
    verbs:
      - get
      - patch
  