apiVersion: v1
kind: Secret
metadata:
  name: couchdb-secret
  namespace: hlf
type: Opaque
data:
  username: {{ .Values.couchdb.username | b64enc }}
  password: {{ .Values.couchdb.password | b64enc }}
---
{{- range $key, $val := .Values.certificates.peer }}
apiVersion: v1
kind: Secret
metadata:
  name: hlfpeer{{ $key }}-idcert
  namespace: hlf
type: Opaque
data:
  cert.pem: {{ $val | b64enc }}
---
{{- end }}
{{- if not .Values.hsm.enabled }}
{{- range $key, $val := .Values.privateKeys.peer }}
apiVersion: v1
kind: Secret
metadata:
  name: hlfpeer{{ $key }}-idkey
  namespace: hlf
type: Opaque
data:
  key.pem: {{ $val | b64enc }}
---
{{- end }}
{{- end }}
{{- range $key, $val := .Values.certificates.peerTls }}
apiVersion: v1
kind: Secret
metadata:
  name: hlfpeer{{ $key }}-tls-idcert
  namespace: hlf
type: Opaque
data:
  server.crt: {{ $val | b64enc }}
---
{{- end }}
{{- range $key, $val := .Values.privateKeys.peerTls }}
apiVersion: v1
kind: Secret
metadata:
  name: hlfpeer{{ $key }}-tls-idkey
  namespace: hlf
type: Opaque
data:
  server.key: {{ $val | b64enc }}
---
{{- end }}
{{- range $key, $val := .Values.certificates.orderer }}
apiVersion: v1
kind: Secret
metadata:
  name: hlforderer{{ $key }}-idcert
  namespace: hlf
type: Opaque
data:
  cert.pem: {{ $val | b64enc }}
---
{{- end }}
{{- if not .Values.hsm.enabled }}
{{- range $key, $val := .Values.privateKeys.orderer }}
apiVersion: v1
kind: Secret
metadata:
  name: hlforderer{{ $key }}-idkey
  namespace: hlf
type: Opaque
data:
  key.pem: {{ $val | b64enc }}
---
{{- end }}
{{- end }}
{{- range $key, $val := .Values.certificates.ordererTls }}
apiVersion: v1
kind: Secret
metadata:
  name: hlforderer{{ $key }}-tls-idcert
  namespace: hlf
type: Opaque
data:
  server.crt: {{ $val | b64enc }}
---
{{- end }}
{{- range $key, $val := .Values.privateKeys.ordererTls }}
apiVersion: v1
kind: Secret
metadata:
  name: hlforderer{{ $key }}-tls-idkey
  namespace: hlf
type: Opaque
data:
  server.key: {{ $val | b64enc }}
---
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: hlf-ca-root-idcert
  namespace: hlf
type: Opaque
data:
  ca.crt: {{ .Values.certificates.caRoot | b64enc }}
---
{{- if not (empty .Values.certificates.caIntermediate) }}
apiVersion: v1
kind: Secret
metadata:
  name: hlf-ca-intermediate-idcert
  namespace: hlf
type: Opaque
data:
  intermediate.crt: {{ .Values.certificates.caIntermediate | b64enc }}
---
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: hlf-ca-root-tls-idcert
  namespace: hlf
type: Opaque
data:
  ca.crt: {{ .Values.certificates.caRootTls | b64enc }}
---
{{- if not (empty .Values.certificates.caIntermediateTls) }}
apiVersion: v1
kind: Secret
metadata:
  name: hlf-ca-intermediate-tls-idcert
  namespace: hlf
type: Opaque
data:
  intermediate.crt: {{ .Values.certificates.caIntermediateTls | b64enc }}
---
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: hlf-ca-chain-tls-idcert
  namespace: hlf
type: Opaque
data:
  chain.crt: |
    {{ include "fabric.cachaincert" . | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: hlf-admin-idcert
  namespace: hlf
type: Opaque
data:
  cert.pem: {{ .Values.certificates.admin | b64enc }}
---
{{- if not .Values.hsm.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: hlf-admin-idkey
  namespace: hlf
type: Opaque
data:
  key.pem: {{ .Values.privateKeys.admin | b64enc }}
---
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: hlf-admin-tls-idcert
  namespace: hlf
type: Opaque
data:
  cert.pem: {{ .Values.certificates.adminTls | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: hlf-admin-tls-idkey
  namespace: hlf
type: Opaque
data:
  key.pem: {{ .Values.privateKeys.adminTls | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: hlf-orderer-admin-idcert
  namespace: hlf
type: Opaque
data:
  cert.pem: {{ .Values.certificates.ordererAdmin | b64enc }}
---
{{- if not .Values.hsm.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: hlf-orderer-admin-idkey
  namespace: hlf
type: Opaque
data:
  key.pem: {{ .Values.privateKeys.ordererAdmin | b64enc }}
---
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: hlf-orderer-admin-tls-idcert
  namespace: hlf
type: Opaque
data:
  cert.pem: {{ .Values.certificates.ordererAdminTls | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: hlf-orderer-admin-tls-idkey
  namespace: hlf
type: Opaque
data:
  key.pem: {{ .Values.privateKeys.ordererAdminTls | b64enc }}
---
{{- if .Values.hsm.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: hsm-server-cert
  namespace: hlf
type: Opaque
data:
  server.pem: {{ .Values.certificates.hsmServer | b64enc }}  
---
apiVersion: v1
kind: Secret
metadata:
  name: hsm-client-cert
  namespace: hlf
type: Opaque
data:
  VMSS01.pem: {{ .Values.certificates.hsmClient | b64enc }} 
---
apiVersion: v1
kind: Secret
metadata:
  name: hsm-client-key
  namespace: hlf
type: Opaque
data:
  VMSS01Key.pem: {{ .Values.privateKeys.hsmClient | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: chrystoki-conf
  namespace: hlf
type: Opaque
data: 
  Chrystoki.conf: |-
    {{ include "fabric.chrystokiconf" . | indent 4 | toString | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: hsm-authentication
  namespace: hlf
type: Opaque
data:
  label: {{ print .Values.hsm.label | b64enc }}
  pin: {{ .Values.hsm.pin | b64enc }}
---
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: hlf-genesis-block
  namespace: hlf
type: Opaque
data:
  genesisblock: {{ include "fabric.genesissecret" . }}
---
apiVersion: v1
kind: Secret
metadata:
  name: hlf-configtx
  namespace: hlf
type: Opaque
data:
  configtx.yaml: |-
    {{ include "fabric.genesisconfigtx" . | indent 4 | toString | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: hlf-peer-configtx
  namespace: hlf
type: Opaque
data:
  configtx.yaml: |-
    {{ include "fabric.postconfigtx" .Values.peer | indent 4 | toString | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: hlf-orderer-configtx
  namespace: hlf
type: Opaque
data:
  configtx.yaml: |-
    {{ include "fabric.postconfigtx" .Values.orderer | indent 4 | toString | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: fabric-scripts
  namespace: hlf
type: Opaque
data:
  fabricScripts.sh: |-
    {{ .Files.Get "files/fabricScripts.sh" | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: hlf-core
  namespace: hlf
type: Opaque
data:
  core.yaml:  |-
    {{ include "fabric.coreyaml" . | indent 4 | toString | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: hlf-orderer-conf
  namespace: hlf
type: Opaque
data:
  orderer.yaml: |-
    {{ .Files.Get "files/orderer.yaml" | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: hlf-test-chaincode
  namespace: hlf
type: Opaque
data:
  chaincode.go: |-
    {{ .Files.Get "files/chaincode.go" | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: registry-secret
  namespace: hlf
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "fabric.dockerconfigjson" .Values.registries.main }}
---
